In [1]:
import torch

In [2]:
data = torch.rand([2,2,3,4])

In [3]:
data,data.shape

(tensor([[[[0.9336, 0.5868, 0.4703, 0.6762],
           [0.3395, 0.2547, 0.3528, 0.4312],
           [0.8470, 0.7189, 0.3222, 0.8064]],
 
          [[0.3665, 0.4545, 0.8921, 0.7179],
           [0.2143, 0.5371, 0.1009, 0.5539],
           [0.6657, 0.3684, 0.8866, 0.0920]]],
 
 
         [[[0.3230, 0.2451, 0.7668, 0.8565],
           [0.5000, 0.8827, 0.5048, 0.2897],
           [0.6108, 0.1333, 0.6312, 0.8688]],
 
          [[0.1111, 0.3878, 0.2625, 0.3767],
           [0.0414, 0.5270, 0.9028, 0.4735],
           [0.7356, 0.6457, 0.5284, 0.7074]]]]),
 torch.Size([2, 2, 3, 4]))

In [4]:
data1 = data.permute(0,2,3,1)

In [237]:
data2 = data1.contiguous().view([-1, data1.shape[3]])

In [238]:
data2

tensor([[0.1460, 0.2241],
        [0.7065, 0.0062],
        [0.2686, 0.1726],
        [0.0681, 0.4390],
        [0.1651, 0.4509],
        [0.3473, 0.6007],
        [0.1755, 0.4506],
        [0.0359, 0.3432],
        [0.1333, 0.5799],
        [0.2825, 0.8839],
        [0.6345, 0.2833],
        [0.5561, 0.9713],
        [0.7025, 0.6293],
        [0.3980, 0.2183],
        [0.0471, 0.0126],
        [0.2567, 0.3113],
        [0.3623, 0.2201],
        [0.5884, 0.9939],
        [0.7515, 0.0899],
        [0.8357, 0.4169],
        [0.5043, 0.0621],
        [0.3229, 0.0965],
        [0.4080, 0.0045],
        [0.6654, 0.8533]])

In [10]:
data = torch.rand([2,3,4])

In [11]:
data

tensor([[[0.4552, 0.9998, 0.4721, 0.0437],
         [0.4753, 0.4354, 0.8355, 0.1161],
         [0.2716, 0.7266, 0.7657, 0.9512]],

        [[0.5957, 0.3744, 0.5922, 0.4576],
         [0.4452, 0.8806, 0.2957, 0.7242],
         [0.2229, 0.1127, 0.0629, 0.9083]]])

In [8]:
data.contiguous().view([-1, 4])

tensor([[0.4411, 0.4464, 0.7167, 0.0962],
        [0.4704, 0.9263, 0.8729, 0.5080],
        [0.3021, 0.9049, 0.0312, 0.4692],
        [0.6298, 0.1067, 0.0690, 0.1407],
        [0.1956, 0.6053, 0.6894, 0.6244],
        [0.2217, 0.9313, 0.1224, 0.8305]])

In [12]:
contrast_feature = torch.cat(torch.unbind(data, dim=1), dim=0)

In [22]:
a = contrast_feature
a

tensor([[0.4552, 0.9998, 0.4721, 0.0437],
        [0.5957, 0.3744, 0.5922, 0.4576],
        [0.4753, 0.4354, 0.8355, 0.1161],
        [0.4452, 0.8806, 0.2957, 0.7242],
        [0.2716, 0.7266, 0.7657, 0.9512],
        [0.2229, 0.1127, 0.0629, 0.9083]])

In [23]:
b = contrast_feature.sum(1,keepdim=True)
b

tensor([[1.9709],
        [2.0200],
        [1.8622],
        [2.3457],
        [2.7151],
        [1.3067]])

In [21]:
a + b

tensor([[2.4261, 2.9707, 2.4431, 2.0146],
        [2.6157, 2.3944, 2.6121, 2.4776],
        [2.3375, 2.2976, 2.6977, 1.9784],
        [2.7909, 3.2262, 2.6413, 3.0698],
        [2.9867, 3.4417, 3.4809, 3.6663],
        [1.5295, 1.4193, 1.3695, 2.2149]])